### ISSUE TITLE
Game_Interpreter.prototype.pluginCommandの長さについて

### ISSUE THREAD

**Issue by triacontane** [AlecYawata/TkoolMV_PluginCommandBook#17]
同メソッドの行数について、すでに400STEPほどに及んでいます。これからコマンドを追加するごとに膨らんでいくことを考えると、別の実装を検討してもいいと思います。
個人的には、Game_Interpreterのイベントコマンドの実装を参考にするのがよいかと思うのですが、どうでしょうか？

**Comment by fftfantt** [comment]
> これからコマンドを追加するごとに膨らんでいくことを考えると、別の実装を検討してもいいと思います。
> おっしゃるとおりだと思います。
> 
> Game_Interpreterのイベントコマンドの実装を参考にするのがよいかと思うのですが
> メソッドごとにprototypeによる継承を行う感じでしょうか？

こういう根幹にかかわる大事な部分は、自分のJavaScriptの知識だとまだ明らかに力不足なのでお任せします^^;

**Comment by triacontane** [comment]
Game_Interpreterの実装を参考に試作しました。ですが、この方法にも競合の可能性が高まる等のデメリットがあるのでアレクさんのご意見も伺いたいと思います。お時間のあるときに見ていただいてもよろしいでしょうか。

https://drive.google.com/open?id=0B4WaOHXr6OJxMHNmbHNLNnFVQ3M

**Comment by AlecYawata** [comment]
すごくいいですね！
今思えば、なんらかしらのプラグインコマンドが動くたびにcommandMapを作っていたら、
重くなりすぎますものね。
このやり方なら、このプラグイン自体の処理を別の任意プラグインで一部だけ上書きできるので、
プラグインを書けるツクラーの人にもいいですね！

競合はたしかに気になりますね・・・根本的な解決ではないですが、
関数の最初を「pluginCommandBook」にすれば、別の人の実装と被る可能性って低くなりますかね。

**Comment by triacontane** [comment]
関数を「pluginCommandBook」+「コマンド名」にしてPull Requestしました。お手数をお掛けしますが、レビューのほどよろしくお願いいたします。

**Comment by triacontane** [comment]
マージされましたのでクローズします。
