### ISSUE TITLE
プラグインコマンド「変数の操作」でのevalの使用について

### ISSUE THREAD

**Issue by fftfantt** [AlecYawata/TkoolMV_PluginCommandBook#21]
プラグインコマンドの「変数の操作」について、イベントエディタのスクリプトと同じような取得をできるようにするため、evalによる式の評価を実装しようかと思っておりますが、あまり任意に入力できるようなところにevalは使用しないほうが良いというのはよく聞きますので、みなさんの意見を参考にさせていただきたいです。
たとえば、先頭を$とした場合、evalによる式の評価を有効にする等でもあまりよろしくないでしょうか？

**Comment by triacontane** [comment]
私もあまり詳しくないのですが、ゲームのプレイヤーが任意で入力した文字列をevalで評価するのはセキュリティ上のリスクがあるかもしれません。ですが、ゲームの作者が任意で入力した文字列をevalで評価するのは問題ないかと思います。（そもそもイベントコマンドのスクリプトや、スキルのダメージ計算式などはそうなっているので）

制御文字と組み合わせて\JS[（スクリプト）]としてもいいかもしれません。

**Comment by fftfantt** [comment]
> 制御文字と組み合わせて\JS[（スクリプト）]としてもいいかもしれません。

たしかに、この制御文字で共通部分に実装したほうが汎用性あるかもしれませんね！
ありがとうございます！　ちょっと作ってみます。

**Comment by fftfantt** [comment]
\JS[（スクリプト）]のスクリプト部分の取り出しを、正規表現の後方参照でやろうとすると、今の自分にとっては難しいですね・・・
単純に置換して残ったものでやるか、検索位置からの文字列切り出し( '\JS[' 以降から最後の ']' まで)なら出来そうなのですが、できるだけ統一したほうがいいですよね・・・

**Comment by fftfantt** [comment]
なんかかんやで何とかできました。
お手すきのときにでもご確認ください。

**Comment by fftfantt** [comment]
完了しましたので、クローズします。
