### ISSUE TITLE
銀行システムのための入力制限付き数値入力

### ISSUE THREAD

**Issue by AlecYawata** [AlecYawata/TkoolMV_PluginCommandBook#8]
今は桁しか指定できないけど、
最大で30までしか入力できないとか（3000Gしか持ってない時に100単位でしかお金を預けられない状況想定）
変更できない桁を用意するとか（100G単位でしか変更できないように）
選択肢のように、表示する場所や背景を変更できるようにしたりする

**Comment by AlecYawata** [comment]
あと、初期値とかも

**Comment by triacontane** [comment]
こちらの件、私のローカル環境で仮実装してみました。なお、初期値については設定対象の変数にもともと代入されている値が使われるようです。他の改修項目とも併せて折を見てPull Requestしようと思います。

**Comment by triacontane** [comment]
同機能がマージされ、リリースされました。このまま特に問題がなければクローズしようかと思います。
